package installer

import (
	"fmt"
	"path/filepath"
	"strings"
)

// configureSteps produces everything after the rootfs copy: on-target config
// files, accounts, initramfs, bootloader, and the unmount that makes the disk
// safe to remove.
//
// Split from Plan purely for readability - it is the same sequence and the
// same []Step.
func configureSteps(r Request, rootDev, fsDev, espDev string, uefi bool) []Step {
	var steps []Step
	add := func(desc string, argv ...string) {
		steps = append(steps, Step{Desc: desc, Argv: argv})
	}
	write := func(desc, path, content string, mode uint32) {
		steps = append(steps, Step{Desc: desc, WritePath: path, Content: content, Mode: mode})
	}
	inTarget := func(p string) string { return filepath.Join(targetMount, p) }

	// --- identity ----------------------------------------------------
	write("Setting hostname", inTarget("/etc/hostname"), r.Hostname+"\n", 0o644)
	// A hostname that resolves to nothing makes sudo and many daemons hang
	// on startup, so seed /etc/hosts alongside it.
	write("Writing /etc/hosts", inTarget("/etc/hosts"), fmt.Sprintf(
		"127.0.0.1\tlocalhost\n::1\t\tlocalhost\n127.0.1.1\t%s\n", r.Hostname), 0o644)

	// --- fstab / crypttab --------------------------------------------
	// The root entry addresses the filesystem by label, not by device node:
	// the disk that was /dev/sda under the installer can be /dev/nvme0n1 or a
	// different SATA port on the next boot. An encrypted root is reached
	// through the mapper node the initramfs creates instead.
	rootSpec := "LABEL=" + rootLabel
	if r.Encrypt {
		rootSpec = "/dev/mapper/" + cryptMapper
	}
	var fstab strings.Builder
	fstab.WriteString("# Generated by osb-installer.\n")
	fstab.WriteString("# <device>\t<mount>\t<type>\t<options>\t<dump>\t<pass>\n")
	fmt.Fprintf(&fstab, "%s\t/\text4\trw,relatime\t0\t1\n", rootSpec)
	if uefi {
		// umask=0077 keeps the ESP root-only: it is FAT, so it carries no
		// permissions of its own and would otherwise be world-readable.
		fmt.Fprintf(&fstab, "LABEL=%s\t/boot/%s\tvfat\trw,noatime,umask=0077\t0\t2\n", espLabel, espMountName)
	}
	fstab.WriteString("tmpfs\t/tmp\ttmpfs\trw,nosuid,nodev\t0\t0\n")
	write("Writing /etc/fstab", inTarget("/etc/fstab"), fstab.String(), 0o644)

	if r.Encrypt {
		// PARTLABEL is stable across renumbering and controller changes, and
		// the GPT layout above named the partition. MBR has no partition
		// labels, so a BIOS install falls back to the device node - the
		// installer warns about this on the summary screen.
		luksSpec := "PARTLABEL=" + rootLabel
		if !uefi {
			luksSpec = rootDev
		}
		write("Writing /etc/crypttab", inTarget("/etc/crypttab"),
			fmt.Sprintf("# Generated by osb-installer.\n%s\t%s\tnone\tluks\n", cryptMapper, luksSpec), 0o600)
	}

	// --- accounts ----------------------------------------------------
	// Passwords are piped to chpasswd rather than passed as arguments, so
	// they never appear in the process list. busybox and shadow both ship a
	// compatible chpasswd.
	if r.RootPassword != "" {
		steps = append(steps, Step{
			Desc:  "Setting root password",
			Argv:  []string{"chroot", targetMount, "chpasswd"},
			Stdin: "root:" + r.RootPassword + "\n",
		})
	} else {
		// No root password means no root login at all - lock the account
		// rather than leave it open with an empty password.
		add("Locking root account", "chroot", targetMount, "passwd", "-l", "root")
	}
	if r.Username != "" {
		add("Creating user "+r.Username,
			"chroot", targetMount, "adduser", "-D", "-s", "/bin/sh", r.Username)
		if r.UserPassword != "" {
			steps = append(steps, Step{
				Desc:  "Setting password for " + r.Username,
				Argv:  []string{"chroot", targetMount, "chpasswd"},
				Stdin: r.Username + ":" + r.UserPassword + "\n",
			})
		}
		// wheel is what su/sudo gate on in the images osb builds.
		add("Adding "+r.Username+" to wheel", "chroot", targetMount, "addgroup", r.Username, "wheel")
	}

	// --- initramfs ---------------------------------------------------
	// An encrypted root is unreachable unless the initramfs carries
	// cryptsetup and the dm-crypt modules. Regenerate it on the target,
	// where the kernel modules and mkinitfs config now live.
	if r.Encrypt {
		write("Enabling cryptsetup in initramfs", inTarget("/etc/mkinitfs/mkinitfs.conf"),
			"features=\"base virtio scsi ext4 ahci nvme usb cryptsetup keymap\"\n", 0o644)
		add("Regenerating initramfs", "chroot", targetMount, "sh", "-c",
			"for kv in /lib/modules/*/; do mkinitfs -o /boot/initramfs \"$(basename \"$kv\")\"; done")
	}

	steps = append(steps, bootloaderSteps(r, rootDev, espDev, uefi)...)

	// --- teardown ----------------------------------------------------
	// Unmount deepest-first, then close the LUKS mapping, so pulling the USB
	// stick straight after the success screen cannot leave a dirty
	// filesystem or a live dm device.
	if uefi {
		add("Unmounting ESP", "umount", inTarget("/boot/"+espMountName))
	}
	add("Unmounting target", "umount", targetMount)
	if r.Encrypt {
		add("Closing LUKS container", "cryptsetup", "close", cryptMapper)
	}
	add("Flushing writes to disk", "sync")

	return steps
}

// bootloaderSteps installs the boot path onto the target.
//
// Secure Boot takes the UKI route: the live medium already carries a signed
// EFI binary that the firmware trusts, and copying it is the whole install.
// Everything else goes through limine, which serves BIOS and UEFI from one
// config - the same reason the limine machines exist.
func bootloaderSteps(r Request, rootDev, espDev string, uefi bool) []Step {
	var steps []Step
	add := func(desc string, argv ...string) {
		steps = append(steps, Step{Desc: desc, Argv: argv})
	}
	inTarget := func(p string) string { return filepath.Join(targetMount, p) }
	espDir := inTarget("/boot/" + espMountName)

	if r.SecureBoot {
		// The UKI has the cmdline baked in and signed, so there is no config
		// to write and nothing here may alter the boot parameters - changing
		// them would invalidate the signature.
		add("Creating EFI directory", "mkdir", "-p", filepath.Join(espDir, "EFI", "BOOT"))
		add("Installing signed UKI",
			"cp", filepath.Join(r.SourceRoot, "boot", "EFI", "BOOT", "BOOTX64.EFI"),
			filepath.Join(espDir, "EFI", "BOOT", "BOOTX64.EFI"))
		return steps
	}

	// Root is addressed the same way fstab addresses it. With encryption the
	// kernel cannot reach the filesystem directly, so the cmdline names the
	// LUKS container and the mapper the initramfs must create.
	cmdline := "root=LABEL=" + rootLabel + " rw"
	if r.Encrypt {
		luksSpec := "PARTLABEL=" + rootLabel
		if !uefi {
			luksSpec = rootDev
		}
		cmdline = fmt.Sprintf("cryptroot=%s cryptdm=%s root=/dev/mapper/%s rw", luksSpec, cryptMapper, cryptMapper)
	}
	cmdline += " console=tty0 console=ttyS0,115200"

	// The kernel and initramfs normally stay on the root filesystem and are
	// addressed by label, so limine reads them straight off ext4.
	conf := limineConf("fslabel("+rootLabel+"):/boot", cmdline)

	if uefi {
		add("Creating EFI directory", "mkdir", "-p", filepath.Join(espDir, "EFI", "BOOT"))
		add("Installing limine EFI binary",
			"cp", "/usr/share/limine/BOOTX64.EFI", filepath.Join(espDir, "EFI", "BOOT", "BOOTX64.EFI"))

		if r.Encrypt {
			// limine cannot read a LUKS container, so an encrypted install
			// keeps the kernel and initramfs unencrypted on the ESP. They
			// land at the ESP root, and boot() addresses the partition limine
			// itself was loaded from - so the paths lose their /boot prefix.
			add("Copying kernel to ESP", "sh", "-c",
				"cp "+inTarget("/boot")+"/vmlinuz* "+inTarget("/boot")+"/initramfs* "+espDir+"/")
			conf = limineConf("boot():", cmdline)
		}
		steps = append(steps, Step{
			Desc: "Writing limine.conf", WritePath: filepath.Join(espDir, "limine.conf"),
			Content: conf, Mode: 0o644,
		})
		return steps
	}

	// BIOS: stage 2 and the config live on the root filesystem, and stage 1
	// goes into the MBR. With encryption neither is readable at boot, so the
	// BIOS+encryption combination is refused before we get here.
	add("Creating /boot/limine", "mkdir", "-p", inTarget("/boot/limine"))
	add("Installing limine BIOS stage 2",
		"cp", "/usr/share/limine/limine-bios.sys", inTarget("/boot/limine/limine-bios.sys"))
	steps = append(steps, Step{
		Desc: "Writing limine.conf", WritePath: inTarget("/boot/limine/limine.conf"),
		Content: conf, Mode: 0o644,
	})
	add("Installing limine to MBR", "limine", "bios-install", r.Disk)
	return steps
}

// limineConf renders the target's boot config. base is the limine path prefix
// the kernel and initramfs are reached through - "fslabel(rootfs):/boot" when
// they sit on the root filesystem, "boot():" when they have been staged onto
// the ESP because root is encrypted.
//
// limine does no globbing, so the config names the exact paths osb's Alpine
// images install: /boot/vmlinuz and /boot/initramfs, without a version suffix.
func limineConf(base, cmdline string) string {
	var b strings.Builder
	b.WriteString("# Generated by osb-installer - rerun the installer to change.\n")
	b.WriteString("timeout: 3\n")
	b.WriteString("serial: yes\n\n")
	b.WriteString("/osb\n")
	b.WriteString("    protocol: linux\n")
	fmt.Fprintf(&b, "    path: %s/vmlinuz\n", base)
	fmt.Fprintf(&b, "    cmdline: %s\n", cmdline)
	fmt.Fprintf(&b, "    module_path: %s/initramfs\n", base)
	return b.String()
}
